grid off
title('Reachable Tube in x y space for time interval [0,4]s','FontSize',16)
hXLabel = xlabel('time');
hYLabel = ylabel('x (m)');
hZLabel = zlabel('y (m)');
set([hXLabel, hYLabel, hZLabel]  , ...
    'FontSize'   , 16          );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'LineWidth'   , 1         , ...
  'FontSize'    , 12);

grid on

axis([0, 4 -3, 5 -5 5])

OptionZ.FrameRate=15;OptionZ.Duration=5.5;OptionZ.Periodic=true;
CaptureFigVid([-20,10;-110,10;-190,80;-290,10;-380,10], 'testvid',OptionZ)
%%
% reachable set
grid off
title('Reachable Set at t=4s','FontSize',16)
hXLabel = xlabel('x (m)');
hYLabel = ylabel('y (m)');
hZLabel = zlabel('z (m)');
set([hXLabel, hYLabel, hZLabel]  , ...
    'FontSize'   , 16          );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'LineWidth'   , 1         , ...
  'FontSize'    , 16);

grid on
%%
%control set
grid off
title('Constraint Control Sets for aircraft A and B','FontSize',16)
hXLabel = xlabel('F (N)');
hYLabel = ylabel('u_1 (N m)');
hZLabel = zlabel('u_2 (N m)');
set([hXLabel, hYLabel, hZLabel]  , ...
    'FontSize'   , 16          );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'LineWidth'   , 1         , ...
  'FontSize'    , 16);

grid on
axis([-0.2, 0.4 -0.2, 0.2 -0.2 0.2])

OptionZ.FrameRate=15;OptionZ.Duration=5.5;OptionZ.Periodic=true;
CaptureFigVid([-20,10;-110,10;-190,80;-290,10;-380,10], 'testvid',OptionZ)